---
abstract: 'Skype API wrapper for Perl'
author:
  - 'Takumi Akiyama <t.akiym at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Skype-Any
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/akiym/Skype-Any.git
version: 0.01
